language: node_js
node_js:
  - '10'
after_success:
  - "BRANCHES_TO_MERGE_REGEX='dev' BRANCH_TO_MERGE_INTO=qa GITHUB_REPO=leolas95/ucabture ./travis-automerge"
deploy:
  provider: heroku
  api_key:
    secure: EpMclDso/xxWE4UteMxY7uhmuxrLPBZHcB36I1TF0DyAeUDq7s00T4UeoXuTDr1cQ9p7Ue+TZ3x9Dk9JNcSy22XNGWzrGP7Mle2SieZrDcIMB8MkrPSoPSUwWYlsIq8kYm3qajXfaWGSD+K4cSQSZCvRwgoIXRFK4ZZqJhW3E4LwWryFPWPLuCH9atIt7B63E0NmV5a9YTg5AQhXNPJsRaemwZvxJq7j2fvEcUZleEG/5SRf4AU+C0J/qnVLtmSqZ6sGJYA4ZVn1reR3+REMLiLPuxWpRIWo44jkiFwGUE/jVi5LRzVujF1XaX9V4KX3gQp/ol/+N9PvWWU/P7ALS75ELfiQm7dVhlm0w+SUZjumhVO18+rP3lflAHukM5OgVkKt2KYV6iSQc1Bt3feu6Z7i4LBBSJDA3V27mkZ4alcGFnKMV7mcOtDgnM30aBKZU168VLdytsfPTN7dTTRRtynsS+Rc0Y8M4cZG5qF9qDGovwTfSbVFSZw+N67dpz9P0BFoarGeREWjxfLz4QVIT8H9QJE6xX9wthgc7AAmPgtNuttwOrWghXExJKDu2bsjJDvVKiY1DzitA69MorHCbw2MshoqrqoMwg7E8RQgb3O17gCrXlXjjugqOOhjKj4TNf0Oj7EG05NNtDDl6tI4TyJRKVnb8biDUOWRVKo8OXY=
  app: ucabture
  on:
    branch: master
    repo: leolas95/ucabture
env:
  global:
    secure: CyhWXNMlEkF9+p+Q97SxagxIvmWRqKW7/ffrrsZQpScLIooAwDhE93VB8cQc0tAR0HkqHC31q74+NQwHq+l2iH/ubVi7+zyD9SqqbZhONx8JO1NArUGWv1DetjSARcpSWP8fta9ZMCoNKKqRfVrmhIzgyXdhOIVT9TD4R1BmYI9xMxxb5fTFY98oEMsvIYDyuf78idIBfQdtd2dodh07EfHzvsQnKEYSqIwAJRO6H/A+Gltn+qk7YexrTLgkyw51gwQPwjNH7TqQCnG41iVi1RFwxzIT+0X7W047a38vdw8972Uue7avIjOQf93e07HQPS3Br0c3lSZ7WgNf7hvq65SaojKEY2XuFZcy2phC6jFy1sUdWfCOCmcobdDgJsf8kwYsTslhet+v5Brz/u86hyuVm6J/Qk8AIZZGwvupI7v7JBjaSTQ8JWlSFiUevBoSUNiBVmh6snST1ItSz6pGTFXcAsHskPbHno3bh/aopfzHcbnifY9PMz3BNTxn/S1UinFJPg7UMbZT2Z9mjnY2k0LmXXtW0ezVI7JAxU0AkdThooh9e63Kkn7Kq4QRtJEvIaUfEbYqi9/NQti5frliNdQ91DzMTm6xl4WdxiNWJgvdcNppO80hbgzgaav3cwfnc15ssfPt1i3pcRvJg0JyFvwPtl1810Gpblw3rlPXdAc=
