language: node_js
node_js:
- '10'
notifications:
  email:
  - milad.zaghab@gmail.com
  - mariamsalloumstanbuly@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: EpMclDso/xxWE4UteMxY7uhmuxrLPBZHcB36I1TF0DyAeUDq7s00T4UeoXuTDr1cQ9p7Ue+TZ3x9Dk9JNcSy22XNGWzrGP7Mle2SieZrDcIMB8MkrPSoPSUwWYlsIq8kYm3qajXfaWGSD+K4cSQSZCvRwgoIXRFK4ZZqJhW3E4LwWryFPWPLuCH9atIt7B63E0NmV5a9YTg5AQhXNPJsRaemwZvxJq7j2fvEcUZleEG/5SRf4AU+C0J/qnVLtmSqZ6sGJYA4ZVn1reR3+REMLiLPuxWpRIWo44jkiFwGUE/jVi5LRzVujF1XaX9V4KX3gQp/ol/+N9PvWWU/P7ALS75ELfiQm7dVhlm0w+SUZjumhVO18+rP3lflAHukM5OgVkKt2KYV6iSQc1Bt3feu6Z7i4LBBSJDA3V27mkZ4alcGFnKMV7mcOtDgnM30aBKZU168VLdytsfPTN7dTTRRtynsS+Rc0Y8M4cZG5qF9qDGovwTfSbVFSZw+N67dpz9P0BFoarGeREWjxfLz4QVIT8H9QJE6xX9wthgc7AAmPgtNuttwOrWghXExJKDu2bsjJDvVKiY1DzitA69MorHCbw2MshoqrqoMwg7E8RQgb3O17gCrXlXjjugqOOhjKj4TNf0Oj7EG05NNtDDl6tI4TyJRKVnb8biDUOWRVKo8OXY=
  app: ucabture
  on:
    repo: leolas95/ucabture
